export interface ProtocolOption {
  name: string
  number: number
  category: ProtocolCategory
  common: boolean
}

export type ProtocolCategory =
  | 'transport'
  | 'control'
  | 'multicast'
  | 'routing'
  | 'redundancy'
  | 'tunneling'
  | 'ipsec'
  | 'signaling'
  | 'other'

export const PROTOCOL_OPTIONS: ProtocolOption[] = [
  { name: 'HOPOPT', number: 0, category: 'other', common: false },
  { name: 'ICMP', number: 1, category: 'control', common: true },
  { name: 'IGMP', number: 2, category: 'multicast', common: true },
  { name: 'GGP', number: 3, category: 'other', common: false },
  { name: 'IPINIP', number: 4, category: 'tunneling', common: true },
  { name: 'ST', number: 5, category: 'other', common: false },
  { name: 'TCP', number: 6, category: 'transport', common: true },
  { name: 'CBT', number: 7, category: 'other', common: false },
  { name: 'EGP', number: 8, category: 'routing', common: true },
  { name: 'IGP', number: 9, category: 'routing', common: false },
  { name: 'BBN_RCC_MON', number: 10, category: 'other', common: false },
  { name: 'NVPII', number: 11, category: 'other', common: false },
  { name: 'PUP', number: 12, category: 'other', common: false },
  { name: 'ARGUS', number: 13, category: 'other', common: false },
  { name: 'EMCON', number: 14, category: 'other', common: false },
  { name: 'XNET', number: 15, category: 'other', common: false },
  { name: 'CHAOS', number: 16, category: 'other', common: false },
  { name: 'UDP', number: 17, category: 'transport', common: true },
  { name: 'MUX', number: 18, category: 'other', common: false },
  { name: 'DCN_MEAS', number: 19, category: 'other', common: false },
  { name: 'HMP', number: 20, category: 'other', common: false },
  { name: 'PRM', number: 21, category: 'other', common: false },
  { name: 'XNS_IDP', number: 22, category: 'other', common: false },
  { name: 'TRUNK1', number: 23, category: 'other', common: false },
  { name: 'TRUNK2', number: 24, category: 'other', common: false },
  { name: 'LEAF1', number: 25, category: 'other', common: false },
  { name: 'LEAF2', number: 26, category: 'other', common: false },
  { name: 'RDP', number: 27, category: 'transport', common: false },
  { name: 'IRTP', number: 28, category: 'other', common: false },
  { name: 'ISO_TP4', number: 29, category: 'other', common: false },
  { name: 'NETBLT', number: 30, category: 'other', common: false },
  { name: 'MFE_NSP', number: 31, category: 'other', common: false },
  { name: 'MERIT_INP', number: 32, category: 'other', common: false },
  { name: 'DCCP', number: 33, category: 'transport', common: true },
  { name: 'THREE_PC', number: 34, category: 'other', common: false },
  { name: 'IDPR', number: 35, category: 'routing', common: false },
  { name: 'XTP', number: 36, category: 'other', common: false },
  { name: 'DDP', number: 37, category: 'other', common: false },
  { name: 'IDPR_CMTP', number: 38, category: 'other', common: false },
  { name: 'TPPLUSPLUS', number: 39, category: 'other', common: false },
  { name: 'IL', number: 40, category: 'other', common: false },
  { name: 'IPV6', number: 41, category: 'tunneling', common: true },
  { name: 'SDRP', number: 42, category: 'other', common: false },
  { name: 'IDRP', number: 45, category: 'routing', common: false },
  { name: 'RSVP', number: 46, category: 'signaling', common: true },
  { name: 'GRE', number: 47, category: 'tunneling', common: true },
  { name: 'MHRP', number: 48, category: 'other', common: false },
  { name: 'BNA', number: 49, category: 'other', common: false },
  { name: 'ESP', number: 50, category: 'ipsec', common: true },
  { name: 'AHP', number: 51, category: 'ipsec', common: true },
  { name: 'I_NLSP', number: 52, category: 'other', common: false },
  { name: 'SWIPE', number: 53, category: 'other', common: false },
  { name: 'NARP', number: 54, category: 'other', common: false },
  { name: 'MOBILE', number: 55, category: 'other', common: false },
  { name: 'TLSP', number: 56, category: 'other', common: false },
  { name: 'SKIP', number: 57, category: 'other', common: false },
  { name: 'IPV6_ICMP', number: 58, category: 'control', common: true },
  { name: 'ANY_HOST_INTERNAL_PROTOCOL', number: 61, category: 'other', common: false },
  { name: 'CFTP', number: 62, category: 'other', common: false },
  { name: 'ANY_LOCAL_NETWORK', number: 63, category: 'other', common: false },
  { name: 'SAT_EXPAK', number: 64, category: 'other', common: false },
  { name: 'KRYPTOLAN', number: 65, category: 'other', common: false },
  { name: 'RVD', number: 66, category: 'other', common: false },
  { name: 'IPPC', number: 67, category: 'other', common: false },
  { name: 'ANY_DISTRIBUTED_FILE_SYSTEM', number: 68, category: 'other', common: false },
  { name: 'SAT_MON', number: 69, category: 'other', common: false },
  { name: 'VISA', number: 70, category: 'other', common: false },
  { name: 'IPCU', number: 71, category: 'other', common: false },
  { name: 'CPNX', number: 72, category: 'other', common: false },
  { name: 'CPHB', number: 73, category: 'other', common: false },
  { name: 'WSN', number: 74, category: 'other', common: false },
  { name: 'PVP', number: 75, category: 'other', common: false },
  { name: 'BR_SAT_MON', number: 76, category: 'other', common: false },
  { name: 'SUN_ND', number: 77, category: 'other', common: false },
  { name: 'WB_MON', number: 78, category: 'other', common: false },
  { name: 'WB_EXPAK', number: 79, category: 'other', common: false },
  { name: 'ISO_IP', number: 80, category: 'other', common: false },
  { name: 'VMTP', number: 81, category: 'other', common: false },
  { name: 'SECURE_VMTP', number: 82, category: 'other', common: false },
  { name: 'VINES', number: 83, category: 'other', common: false },
  { name: 'TTP', number: 84, category: 'other', common: false },
  { name: 'NSFNET_IGP', number: 85, category: 'routing', common: false },
  { name: 'DGP', number: 86, category: 'other', common: false },
  { name: 'TCF', number: 87, category: 'other', common: false },
  { name: 'EIGRP', number: 88, category: 'routing', common: true },
  { name: 'OSPF', number: 89, category: 'routing', common: true },
  { name: 'SPRITE_RPC', number: 90, category: 'other', common: false },
  { name: 'LARP', number: 91, category: 'other', common: false },
  { name: 'MTP', number: 92, category: 'other', common: false },
  { name: 'AX25', number: 93, category: 'other', common: false },
  { name: 'IPIP', number: 94, category: 'tunneling', common: false },
  { name: 'MICP', number: 95, category: 'other', common: false },
  { name: 'SCC_SP', number: 96, category: 'other', common: false },
  { name: 'ETHERIP', number: 97, category: 'tunneling', common: false },
  { name: 'ENCAP', number: 98, category: 'other', common: false },
  { name: 'ANY_PRIVATE_ENCRYPTION_SCHEME', number: 99, category: 'other', common: false },
  { name: 'GMTP', number: 100, category: 'other', common: false },
  { name: 'IFMP', number: 101, category: 'other', common: false },
  { name: 'PNNI', number: 102, category: 'other', common: false },
  { name: 'PIM', number: 103, category: 'multicast', common: true },
  { name: 'ARIS', number: 104, category: 'other', common: false },
  { name: 'SCPS', number: 105, category: 'other', common: false },
  { name: 'QNX', number: 106, category: 'other', common: false },
  { name: 'AN', number: 107, category: 'other', common: false },
  { name: 'IPCOMP', number: 108, category: 'ipsec', common: false },
  { name: 'SNP', number: 109, category: 'other', common: false },
  { name: 'COMPAQ_PEER', number: 110, category: 'other', common: false },
  { name: 'IPX_IN_IP', number: 111, category: 'tunneling', common: false },
  { name: 'VRRP', number: 112, category: 'redundancy', common: true },
  { name: 'PGM', number: 113, category: 'multicast', common: false },
  { name: 'ANY_0_HOP_PROTOCOL', number: 114, category: 'other', common: false },
  { name: 'L2TP', number: 115, category: 'tunneling', common: true },
  { name: 'DDX', number: 116, category: 'other', common: false },
  { name: 'IATP', number: 117, category: 'other', common: false },
  { name: 'STP', number: 118, category: 'other', common: false },
  { name: 'SRP', number: 119, category: 'other', common: false },
  { name: 'UTI', number: 120, category: 'other', common: false },
  { name: 'SMP', number: 121, category: 'other', common: false },
  { name: 'SM', number: 122, category: 'other', common: false },
  { name: 'PTP', number: 123, category: 'other', common: false },
  { name: 'ISIS', number: 124, category: 'routing', common: false },
  { name: 'FIRE', number: 125, category: 'other', common: false },
  { name: 'CRTP', number: 126, category: 'other', common: false },
  { name: 'CRUDP', number: 127, category: 'other', common: false },
  { name: 'SSCOPMCE', number: 128, category: 'other', common: false },
  { name: 'IPLT', number: 129, category: 'other', common: false },
  { name: 'SPS', number: 130, category: 'other', common: false },
  { name: 'PIPE', number: 131, category: 'other', common: false },
  { name: 'SCTP', number: 132, category: 'transport', common: true },
  { name: 'FC', number: 133, category: 'other', common: false },
  { name: 'RSVP_E2E_IGNORE', number: 134, category: 'signaling', common: false },
  { name: 'MOBILITY', number: 135, category: 'other', common: false },
  { name: 'UDP_LITE', number: 136, category: 'transport', common: false },
  { name: 'MPLS_IN_IP', number: 137, category: 'tunneling', common: false },
  { name: 'MANAET', number: 138, category: 'other', common: false },
  { name: 'HIP', number: 139, category: 'other', common: false },
  { name: 'SHIM6', number: 140, category: 'other', common: false },
  { name: 'WESP', number: 141, category: 'ipsec', common: false },
  { name: 'ROHC', number: 142, category: 'other', common: false },
]

export const PROTOCOL_CATEGORIES: Record<ProtocolCategory, string> = {
  transport: 'Transport',
  control: 'Control',
  multicast: 'Multicast',
  routing: 'Routing',
  redundancy: 'Redundancy',
  tunneling: 'Tunneling',
  ipsec: 'IPsec',
  signaling: 'Signaling',
  other: 'Other',
}

export const COMMON_PROTOCOLS = PROTOCOL_OPTIONS.filter(p => p.common)
